const DISCOUNT_TYPE = {
  FIXED_VALUE: 'FIXED_VALUE',
  PERCENTAGE: 'PERCENTAGE',
}

const APPLICABLE_PRODUCTS = {
  ALL: 'ALL',
  SPECIFIC: 'SPECIFIC',
}

module.exports = {
  DISCOUNT_TYPE,
  APPLICABLE_PRODUCTS,
}
